//
//  PokemonData.swift
//  PokeRemember
//
//  Created by David Ulvan on 2023-10-09.
//

import Foundation

struct PokemonEntry:Identifiable {
    var id = UUID()
    var name: String
    var urlPicture: String
    var dexNo: Int
}

let pokeArray = [
    PokemonEntry(name: "Bulbasaur", urlPicture: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/1.png", dexNo:1),
    PokemonEntry(name: "Ivysaur", urlPicture: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/2.png", dexNo:2),
    PokemonEntry(name: "Venusaur", urlPicture: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/3.png", dexNo:3),
    PokemonEntry(name: "Charmander", urlPicture: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/4.png", dexNo: 4),
        PokemonEntry(name: "Charmeleon", urlPicture: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/5.png", dexNo: 5),
        PokemonEntry(name: "Charizard", urlPicture: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/6.png", dexNo: 6),
    PokemonEntry(name: "Squirtle", urlPicture: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/7.png", dexNo: 7),
       PokemonEntry(name: "Wartortle", urlPicture: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/8.png", dexNo: 8),
       PokemonEntry(name: "Blastoise", urlPicture: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/9.png", dexNo: 9),
    PokemonEntry(name: "Caterpie", urlPicture: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/10.png", dexNo: 10),
       PokemonEntry(name: "Metapod", urlPicture: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/11.png", dexNo: 11),
       PokemonEntry(name: "Butterfree", urlPicture: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/12.png", dexNo: 12),
       PokemonEntry(name: "Weedle", urlPicture: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/13.png", dexNo: 13),
       PokemonEntry(name: "Kakuna", urlPicture: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/14.png", dexNo: 14),
       PokemonEntry(name: "Beedrill", urlPicture: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/15.png", dexNo: 15),
       PokemonEntry(name: "Pidgey", urlPicture: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/16.png", dexNo: 16),
       PokemonEntry(name: "Pidgeotto", urlPicture: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/17.png", dexNo: 17),
       PokemonEntry(name: "Pidgeot", urlPicture: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/18.png", dexNo: 18),
       PokemonEntry(name: "Rattata", urlPicture: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/19.png", dexNo: 19),
       PokemonEntry(name: "Raticate", urlPicture: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/20.png", dexNo: 20),
    PokemonEntry(name: "Spearow", urlPicture: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/21.png", dexNo: 21),
       PokemonEntry(name: "Fearow", urlPicture: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/22.png", dexNo: 22),
       PokemonEntry(name: "Ekans", urlPicture: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/23.png", dexNo: 23),
       PokemonEntry(name: "Arbok", urlPicture: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/24.png", dexNo: 24),
       PokemonEntry(name: "Pikachu", urlPicture: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/25.png", dexNo: 25),
       PokemonEntry(name: "Raichu", urlPicture: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/26.png", dexNo: 26),
       PokemonEntry(name: "Sandshrew", urlPicture: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/27.png", dexNo: 27),
       PokemonEntry(name: "Sandslash", urlPicture: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/28.png", dexNo: 28),
       PokemonEntry(name: "Nidoran♀", urlPicture: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/29.png", dexNo: 29),
       PokemonEntry(name: "Nidorina", urlPicture: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/30.png", dexNo: 30),
    PokemonEntry(name: "Nidoqueen", urlPicture: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/31.png", dexNo: 31),
       PokemonEntry(name: "Nidoran♂", urlPicture: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/32.png", dexNo: 32),
       PokemonEntry(name: "Nidorino", urlPicture: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/33.png", dexNo: 33),
       PokemonEntry(name: "Nidoking", urlPicture: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/34.png", dexNo: 34),
       PokemonEntry(name: "Clefairy", urlPicture: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/35.png", dexNo: 35),
       PokemonEntry(name: "Clefable", urlPicture: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/36.png", dexNo: 36),
       PokemonEntry(name: "Vulpix", urlPicture: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/37.png", dexNo: 37),
       PokemonEntry(name: "Ninetales", urlPicture: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/38.png", dexNo: 38),
       PokemonEntry(name: "Jigglypuff", urlPicture: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/39.png", dexNo: 39),
       PokemonEntry(name: "Wigglytuff", urlPicture: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/40.png", dexNo: 40),
    PokemonEntry(name: "Zubat", urlPicture: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/41.png", dexNo: 41),
        PokemonEntry(name: "Golbat", urlPicture: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/42.png", dexNo: 42),
        PokemonEntry(name: "Oddish", urlPicture: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/43.png", dexNo: 43),
        PokemonEntry(name: "Gloom", urlPicture: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/44.png", dexNo: 44),
        PokemonEntry(name: "Vileplume", urlPicture: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/45.png", dexNo: 45),
        PokemonEntry(name: "Paras", urlPicture: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/46.png", dexNo: 46),
        PokemonEntry(name: "Parasect", urlPicture: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/47.png", dexNo: 47),
        PokemonEntry(name: "Venonat", urlPicture: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/48.png", dexNo: 48),
        PokemonEntry(name: "Venomoth", urlPicture: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/49.png", dexNo: 49),
        PokemonEntry(name: "Diglett", urlPicture: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/50.png", dexNo: 50),
    PokemonEntry(name: "Dugtrio", urlPicture: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/51.png", dexNo: 51),
        PokemonEntry(name: "Meowth", urlPicture: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/52.png", dexNo: 52),
        PokemonEntry(name: "Persian", urlPicture: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/53.png", dexNo: 53),
        PokemonEntry(name: "Psyduck", urlPicture: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/54.png", dexNo: 54),
        PokemonEntry(name: "Golduck", urlPicture: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/55.png", dexNo: 55),
        PokemonEntry(name: "Mankey", urlPicture: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/56.png", dexNo: 56),
        PokemonEntry(name: "Primeape", urlPicture: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/57.png", dexNo: 57),
        PokemonEntry(name: "Growlithe", urlPicture: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/58.png", dexNo: 58),
        PokemonEntry(name: "Arcanine", urlPicture: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/59.png", dexNo: 59),
        PokemonEntry(name: "Poliwag", urlPicture: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/60.png", dexNo: 60),
    PokemonEntry(name: "Poliwhirl", urlPicture: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/61.png", dexNo: 61),
        PokemonEntry(name: "Poliwrath", urlPicture: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/62.png", dexNo: 62),
        PokemonEntry(name: "Abra", urlPicture: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/63.png", dexNo: 63),
        PokemonEntry(name: "Kadabra", urlPicture: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/64.png", dexNo: 64),
        PokemonEntry(name: "Alakazam", urlPicture: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/65.png", dexNo: 65),
        PokemonEntry(name: "Machop", urlPicture: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/66.png", dexNo: 66),
        PokemonEntry(name: "Machoke", urlPicture: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/67.png", dexNo: 67),
        PokemonEntry(name: "Machamp", urlPicture: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/68.png", dexNo: 68),
        PokemonEntry(name: "Bellsprout", urlPicture: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/69.png", dexNo: 69),
        PokemonEntry(name: "Weepinbell", urlPicture: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/70.png", dexNo: 70),
        PokemonEntry(name: "Victreebel", urlPicture: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/71.png", dexNo: 71),
        PokemonEntry(name: "Tentacool", urlPicture: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/72.png", dexNo: 72),
        PokemonEntry(name: "Tentacruel", urlPicture: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/73.png", dexNo: 73),
        PokemonEntry(name: "Geodude", urlPicture: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/74.png", dexNo: 74),
        PokemonEntry(name: "Graveler", urlPicture: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/75.png", dexNo: 75),
        PokemonEntry(name: "Golem", urlPicture: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/76.png", dexNo: 76),
        PokemonEntry(name: "Ponyta", urlPicture: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/77.png", dexNo: 77),
        PokemonEntry(name: "Rapidash", urlPicture: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/78.png", dexNo: 78),
        PokemonEntry(name: "Slowpoke", urlPicture: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/79.png", dexNo: 79),
        PokemonEntry(name: "Slowbro", urlPicture: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/80.png", dexNo: 80),
    PokemonEntry(name: "Magnemite", urlPicture: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/81.png", dexNo: 81),
    PokemonEntry(name: "Magneton", urlPicture: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/82.png", dexNo: 82),
    PokemonEntry(name: "Farfetch'd", urlPicture: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/83.png", dexNo: 83),
    PokemonEntry(name: "Doduo", urlPicture: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/84.png", dexNo: 84),
    PokemonEntry(name: "Dodrio", urlPicture: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/85.png", dexNo: 85),
    PokemonEntry(name: "Seel", urlPicture: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/86.png", dexNo: 86),
    PokemonEntry(name: "Dewgong", urlPicture: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/87.png", dexNo: 87),
    PokemonEntry(name: "Grimer", urlPicture: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/88.png", dexNo: 88),
    PokemonEntry(name: "Muk", urlPicture: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/89.png", dexNo: 89),
    PokemonEntry(name: "Shellder", urlPicture: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/90.png", dexNo: 90),
    PokemonEntry(name: "Cloyster", urlPicture: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/91.png", dexNo: 91),
    PokemonEntry(name: "Gastly", urlPicture: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/92.png", dexNo: 92),
    PokemonEntry(name: "Haunter", urlPicture: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/93.png", dexNo: 93),
    PokemonEntry(name: "Gengar", urlPicture: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/94.png", dexNo: 94),
    PokemonEntry(name: "Onix", urlPicture: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/95.png", dexNo: 95),
    PokemonEntry(name: "Drowzee", urlPicture: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/96.png", dexNo: 96),
    PokemonEntry(name: "Hypno", urlPicture: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/97.png", dexNo: 97),
    PokemonEntry(name: "Krabby", urlPicture: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/98.png", dexNo: 98),
    PokemonEntry(name: "Kingler", urlPicture: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/99.png", dexNo: 99),
    PokemonEntry(name: "Voltorb", urlPicture: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/100.png", dexNo: 100),
    PokemonEntry(name: "Electrode", urlPicture: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/101.png", dexNo: 101),
    PokemonEntry(name: "Exeggcute", urlPicture: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/102.png", dexNo: 102),
    PokemonEntry(name: "Exeggutor", urlPicture: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/103.png", dexNo: 103),
    PokemonEntry(name: "Cubone", urlPicture: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/104.png", dexNo: 104),
    PokemonEntry(name: "Marowak", urlPicture: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/105.png", dexNo: 105),
    PokemonEntry(name: "Hitmonlee", urlPicture: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/106.png", dexNo: 106),
    PokemonEntry(name: "Hitmonchan", urlPicture: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/107.png", dexNo: 107),
    PokemonEntry(name: "Lickitung", urlPicture: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/108.png", dexNo: 108),
    PokemonEntry(name: "Koffing", urlPicture: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/109.png", dexNo: 109),
    PokemonEntry(name: "Weezing", urlPicture: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/110.png", dexNo: 110),
    PokemonEntry(name: "Rhyhorn", urlPicture: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/111.png", dexNo: 111),
    PokemonEntry(name: "Rhydon", urlPicture: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/112.png", dexNo: 112),
    PokemonEntry(name: "Chansey", urlPicture: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/113.png", dexNo: 113),
    PokemonEntry(name: "Tangela", urlPicture: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/114.png", dexNo: 114),
    PokemonEntry(name: "Kangaskhan", urlPicture: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/115.png", dexNo: 115),
    PokemonEntry(name: "Horsea", urlPicture: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/116.png", dexNo: 116),
    PokemonEntry(name: "Seadra", urlPicture: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/117.png", dexNo: 117),
    PokemonEntry(name: "Goldeen", urlPicture: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/118.png", dexNo: 118),
    PokemonEntry(name: "Seaking", urlPicture: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/119.png", dexNo: 119),
    PokemonEntry(name: "Staryu", urlPicture: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/120.png", dexNo: 120),
    PokemonEntry(name: "Starmie", urlPicture: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/121.png", dexNo: 121),
    PokemonEntry(name: "Mr. Mime", urlPicture: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/122.png", dexNo: 122),
    PokemonEntry(name: "Scyther", urlPicture: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/123.png", dexNo: 123),
    PokemonEntry(name: "Jynx", urlPicture: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/124.png", dexNo: 124),
    PokemonEntry(name: "Electabuzz", urlPicture: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/125.png", dexNo: 125),
    PokemonEntry(name: "Magmar", urlPicture: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/126.png", dexNo: 126),
    PokemonEntry(name: "Pinsir", urlPicture: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/127.png", dexNo: 127),
    PokemonEntry(name: "Tauros", urlPicture: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/128.png", dexNo: 128),
    PokemonEntry(name: "Magikarp", urlPicture: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/129.png", dexNo: 129),
    PokemonEntry(name: "Gyarados", urlPicture: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/130.png", dexNo: 130),
    PokemonEntry(name: "Lapras", urlPicture: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/131.png", dexNo: 131),
    PokemonEntry(name: "Ditto", urlPicture: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/132.png", dexNo: 132),
    PokemonEntry(name: "Eevee", urlPicture: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/133.png", dexNo: 133),
    PokemonEntry(name: "Vaporeon", urlPicture: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/134.png", dexNo: 134),
    PokemonEntry(name: "Jolteon", urlPicture: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/135.png", dexNo: 135),
    PokemonEntry(name: "Flareon", urlPicture: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/136.png", dexNo: 136),
    PokemonEntry(name: "Porygon", urlPicture: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/137.png", dexNo: 137),
    PokemonEntry(name: "Omanyte", urlPicture: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/138.png", dexNo: 138),
    PokemonEntry(name: "Omastar", urlPicture: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/139.png", dexNo: 139),
    PokemonEntry(name: "Kabuto", urlPicture: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/140.png", dexNo: 140),
    PokemonEntry(name: "Kabutops", urlPicture: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/141.png", dexNo: 141),
    PokemonEntry(name: "Aerodactyl", urlPicture: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/142.png", dexNo: 142),
    PokemonEntry(name: "Snorlax", urlPicture: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/143.png", dexNo: 143),
    PokemonEntry(name: "Articuno", urlPicture: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/144.png", dexNo: 144),
    PokemonEntry(name: "Zapdos", urlPicture: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/145.png", dexNo: 145),
    PokemonEntry(name: "Moltres", urlPicture: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/146.png", dexNo: 146),
    PokemonEntry(name: "Dratini", urlPicture: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/147.png", dexNo: 147),
    PokemonEntry(name: "Dragonair", urlPicture: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/148.png", dexNo: 148),
    PokemonEntry(name: "Dragonite", urlPicture: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/149.png", dexNo: 149),
    PokemonEntry(name: "Mewtwo", urlPicture: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/150.png", dexNo: 150),
    PokemonEntry(name: "Mew", urlPicture: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/151.png", dexNo: 151),
    PokemonEntry(name: "Chikorita", urlPicture: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/152.png", dexNo: 152),
    PokemonEntry(name: "Bayleef", urlPicture: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/153.png", dexNo: 153),
    PokemonEntry(name: "Meganium", urlPicture: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/154.png", dexNo: 154),
    PokemonEntry(name: "Cyndaquil", urlPicture: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/155.png", dexNo: 155),
    PokemonEntry(name: "Quilava", urlPicture: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/156.png", dexNo: 156),
    PokemonEntry(name: "Typhlosion", urlPicture: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/157.png", dexNo: 157),
    PokemonEntry(name: "Totodile", urlPicture: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/158.png", dexNo: 158),
    PokemonEntry(name: "Croconaw", urlPicture: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/159.png", dexNo: 159),
    PokemonEntry(name: "Feraligatr", urlPicture: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/160.png", dexNo: 160)
]

/*
 PokemonEntry(name: "Golduck", urlPicture: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/55.png", dexNo:55),
 PokemonEntry(name: "Pikachu", urlPicture: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/25.png", dexNo:25)
 */
